- name: import common role tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: import common role tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: import common role tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: mongo-setup

- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes